### ISSUE TITLE
Bloat spawned two keys

### ISSUE THREAD

**Issue by drrich** [ChrisNZL/Tallowmere2#128]
0.0.8:  I triggered a bloat to explode and he spawned two keys.

**Comment by ChrisNZL** [comment]
Hmm, I haven't been able to reproduce this.

Once 0.0.9 is live, maybe please try keeping an eye out again, and post again if it happens again.

**Comment by ChrisNZL** [comment]
Can't quite confirm, but for v0.0.9 I have added a check to the Creature.Slay method to help ensure a double-death doesn't get triggered somehow, in case this was the issue.

**Comment by ChrisNZL** [comment]
Haven't seen this in a long time, I assume it's fixed, closing for now.
