### ISSUE TITLE
0.0.10 Enemy in floor, graphics glitches

### ISSUE THREAD

**Issue by drrich** [ChrisNZL/Tallowmere2#165]
![2018-11-29-213450_1600x900_scrot](https://user-images.githubusercontent.com/25667623/49267229-06cc0e80-f41f-11e8-96d9-3152224f00f4.png)

**Comment by drrich** [comment]
The graphics glitch was the fire effect in a line below the enemy in the floor there.  (Note that this is a 'Simply Spitting' level)

**Comment by ChrisNZL** [comment]
Fixed in v0.0.11.
