### ISSUE TITLE
No key

### ISSUE THREAD

**Issue by drrich** [ChrisNZL/Tallowmere2#168]
I had a level that seems to have no key; this has happened with an opponent in a block, but there are no such opponents visible on this one.

**Comment by ChrisNZL** [comment]
Any errors in the output log?
Can you please email me your savefile? chris@tallowmere.com

Tallowmere2_OutputLog.txt should be beside the app's executable - you can find this by going Steam > Right-click Tallowmere 2 > Properties > Local Files tab > Browse Local Files.

The output log should also state where your savefile directory is.

**Comment by ChrisNZL** [comment]
For v0.0.11, I am adding a Debug Panel option, "Show Key Info".

You'll be able to activate this by going Options > Advanced, then tick both
`Show Debug Panel` and `Show Key Info`:

![image](https://user-images.githubusercontent.com/280814/49338309-5a8b6180-f684-11e8-9317-57ebd7c6ea13.png)

This will present an overlay that could look something like these:

![image](https://user-images.githubusercontent.com/280814/49338298-4cd5dc00-f684-11e8-9b7f-4fed349a127b.png)
![image](https://user-images.githubusercontent.com/280814/49338532-0930a180-f687-11e8-8ea1-ce3f964017f5.png)

Info:
- **Pending keys:** Number of keys in the current room that are inside enemy bellies, waiting to come out when its parent creature dies.
- **KeyStructs in current room:** Number of keys in the game world's database that are currently in the room on the ground (eg not inside a creature nor being held).
- **Instantiated keys:** Number of physical object keys that have been created based on the KeyStruct data.
- **Temporary keys held:** Number of keys that are currently being held by a creature (eg when you pick up a key).
- **Instantiated key world position:** Position of the instantiated key. If this number is constantly moving, it means the key is falling.

Once a key is consumed by a door, these numbers should reset to 0, and then the next room should start with a Pending Keys of 1 again.

The `KeyStructs` and `Instantiated keys` counts should always match up. If KeyStructs is ever 1 but Instantiated keys is 0, this would definitely be a bug so please report as so if you spot this (need output log and savefile immediately please).

If Instantiated keys is ever 1 but you can't spot the key anywhere in the room, the world position info will be helpful when debugging with your savefile.

Or if you haven't opened the door yet, and all the numbers are zero, all the mobs have been slain, and the key isn't in the home room, then that's a bug too; please submit logs and savefiles.

I'll try to reply here again once the v0.0.11 patch is live.

**Comment by ChrisNZL** [comment]
Seems fixed? Closing for now.

**Comment by ChrisNZL** [comment]
Re-opening. Seems to be an issue again, especially when playing online with 0.1.3.
