### ISSUE TITLE
0.0.10---double key spawn

### ISSUE THREAD

**Issue by drrich** [ChrisNZL/Tallowmere2#189]
Double Trouble room---each enemy of the pair spawned a key.

**Comment by drrich** [comment]
Update:  previous error reported on 0.0.11, but I think it's actually 0.0.10 as my Linux machine (Manjaro) was not up to date.

**Comment by ChrisNZL** [comment]
Dupe of #173, should be fixed in v0.0.11, no worries thanks :)
