### ISSUE TITLE
Null ref when fighting Hydra with Scythe

### ISSUE THREAD

**Issue by drrich** [ChrisNZL/Tallowmere2#216]
0.0.13:  I had just finished the regular part of level 10 and had unlocked the Hydra Room.  The critical error happened several times as I was switching weapons; as I was trying to determine what was happening, the game eventually crashed (probably after 4--7 critical errors, if that helps...).  Log attached.

[Tallowmere2_OutputLog.txt](https://github.com/ChrisNZL/Tallowmere2/files/2762366/Tallowmere2_OutputLog.txt)

**Comment by ChrisNZL** [comment]
Fixed in v0.0.13a.
