### ISSUE TITLE
Arcane staffers miss

### ISSUE THREAD

**Issue by drrich** [ChrisNZL/Tallowmere2#249]
The mages with the staves are missing when you're too close.  I first noticed when I went to block and the projectile spawned past my shield---pushing into them makes the projectile spawn behind the player, causing them to miss.  (Dunno if this is a feature or a bug... :D )

**Comment by ChrisNZL** [comment]
Thanks. Fixed in v0.0.15. Moved the projectile spawn point back a little bit on the Elemental Staff weapon so that it should collide with a creature that's right in front of you.
