### ISSUE TITLE
Poison screen effect is laggy

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#25]
Too many particles.

**Comment by tylerrrr07** [comment]
I assumed most of my lag was coming from ticks of Flash of Light. Could be both!

**Comment by ChrisNZL** [comment]
From what I can tell, the lag is actually caused from the UI shaking, due to how Unity's Canvas rendering works. If you disable the "Shake UI" option, the lag should go away.

Frame rate seems stable if the shake is disabled.

TODO later on: add option to modify how intense the poison screen effect is.

**Comment by ChrisNZL** [comment]
From further testing, there's maybe a slight performance degrade at times.
I'll try reducing the emission rate from `700` to `400` for now.
