### ISSUE TITLE
Hide cursor

### ISSUE THREAD

**Issue by drrich** [ChrisNZL/Tallowmere2#250]
I would suggest hiding the cursor when the mouse is inactive for a short period of time and not showing it again until it is moved again.  (I play by keyboard and that cursor just gets in the way.)

**Comment by ChrisNZL** [comment]
Fixed in v0.0.15.
Added an input option, **Always Show Mouse Cursor**, disabled by default:

> If enabled, the mouse cursor will always be visible.
>
> If disabled, the mouse cursor will hide automatically, and will only show when you move the mouse on certain menu screens.
