### ISSUE TITLE
Level up bonus reward "+0 Gold Find"

### ISSUE THREAD

**Issue by sePL80** [ChrisNZL/Tallowmere2#294]
Leveling up, there was a bonus reward of "+0 Gold Find" on the "Strength" path.
screenshot:
https://abload.de/img/0goldfind4ojla.jpg

**Comment by ChrisNZL** [comment]
Thanks for reporting this.

Fixed in v0.0.15c coming up.

Turns out this was actually a "gain instant gold" bonus reward, but was using the wrong StringID and parsing the wrong number.

Cheers
