### ISSUE TITLE
Add weapon / equipment / item management

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#655]
Need to be able to:
- Mark items as junk (issue #283)
- Rearrange order of items for both Inventory menus and Weapon Selector
- Sort weapons by type, damage, rarity, other stats, etc
- Implement issue #612 for auto-equipping or not

**Comment by ChrisNZL** [comment]
Additional suggestion:
- Allow items to be "locked" so they can't be sold accidentally.

**Comment by ChrisNZL** [comment]
Further idea:
- Allow <kbd>Shift</kbd> + <kbd>1-8</kbd> be used for shield shortcuts.

**Comment by ChrisNZL** [comment]
Potion management:
- Order of potions
- Allow potions to appear on Weapon Selector, including health amount

Weapon Selector:
- Maybe even add multiple types of selectors, one for weapons, one for shields, one for potions, etc – tabbable via <kbd>LT</kbd> or <kbd>RT</kbd>, and keyboard keys.

**Comment by deathxxx123** [comment]
Just we can mark any item from stash with hot key, like F1 ... to F12, just like Diablo 2. And then in-game when press some hot key, we can use any market potion, shield, weapon. This will be a super fast usage.
And we can use like Shift + F1 to mark any item desired, then use F1 in game to use this item.

**Comment by ChrisNZL** [comment]
Improvements/additions for 0.2.7:

# Sorting items

Filters have been added to the following tabs:
- Inventory > Weapons, Shields, Potions
- Merchant > Buy, Sell, Buyback

![image](https://user-images.githubusercontent.com/280814/120250230-79a8ef80-c2d1-11eb-9515-602cc66d8857.png)

Filters include Sort By options such as:
- Attack Power / Health / Strength
- Item Type / Weapon Type
- Element
- Gold Value
- Modifier Count
- Quantity

When refreshing a category, items marked as Junk will appear after non-junk items.

# Keyboard Weapon Shortcuts

Added option for keyboard shortcuts: **Options > Input > Weapon Shortcuts**

The default **Automatic** option will respect how weapons appear on your Weapon Selector, which can be modified from the **Inventory > Loadout** tab.

For custom shortcuts, the **Manual** option lets you assign specific numbers, irrespective of which weapon is in which Loadout slot.

User can select one of three options:
## 1. Automatic (default)
> If weapon shortcuts are Automatic, you can press number keys 1–9 to select weapons based on your Weapon Selector loadout slots.
>
> Automatic does not allow for manual assigning.

## 2. Manual
> If weapon shortcuts are Manual, you can assign weapons to number keys 1–9 as desired, regardless of slot order.
>
> **To assign a shortcut:**
> - Equip a weapon.
> - Hold <kbd>Alt</kbd> or <kbd>Ctrl</kbd>, then press a number.
> - A notification will confirm the shortcut has been assigned.
>
> **To load a shortcut:**
> - Press the assigned number key by itself. Note that this only works if no menus are showing.

## 3. Off
> If weapon shortcuts are Off, number keys will not access weapons at all.

When browsing your inventory, keyboard shortcut numbers will appear on the weapon's info.

![image](https://user-images.githubusercontent.com/280814/120250270-9ba27200-c2d1-11eb-897e-5656bc3b42ef.png)

### Note with Manual assigning
For 0.2.7, to assign a shortcut, the Inventory menu has to be closed. Then, equip your desired weapon, then press <kbd>Ctrl</kbd>+<kbd>1-9</kbd> or <kbd>Alt</kbd>+<kbd>1-9</kbd>.

I may look at allowing shortcuts to be assigned whilst in the menus in a later patch.
