### ISSUE TITLE
Add option: Auto-attack

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#749]
Not everyone likes physically spamming buttons. Fingers get sore.

Investigate adding an option to auto-attack by holding a button down.

**Comment by deathxxx123** [comment]
> Not everyone likes physically spamming buttons. Fingers get sore.
> 
> Investigate adding an option to auto-attack by holding a button down.

This can be done, using steam controller options, via steam big picture mode. You can enable any key from controller to get auto-clicking fast as you like.

**Comment by ChrisNZL** [comment]
Added in 0.2.6 under Options > Advanced.

Not sure if will be enabled by default or not – need to decide yet.
